// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-Ce35EtIyql4tgFwTAVVu1XA-mw4JxWU',
    appId: '1:47594733996:web:9608e1259a279aa574ba09',
    messagingSenderId: '47594733996',
    projectId: 'test-6b603',
    authDomain: 'test-6b603.firebaseapp.com',
    storageBucket: 'test-6b603.firebasestorage.app',
    measurementId: 'G-D5N6PTDJ7M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3CqzI0rxLIixYf1lcdc2UjM9iWKMELK4',
    appId: '1:47594733996:android:9c38cf43102a233074ba09',
    messagingSenderId: '47594733996',
    projectId: 'test-6b603',
    storageBucket: 'test-6b603.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1QiTFdMbkYq-pq7TFHEViZCEWbe-OEhE',
    appId: '1:47594733996:ios:09364dcac91160a274ba09',
    messagingSenderId: '47594733996',
    projectId: 'test-6b603',
    storageBucket: 'test-6b603.firebasestorage.app',
    iosBundleId: 'com.example.loginSignupPages',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1QiTFdMbkYq-pq7TFHEViZCEWbe-OEhE',
    appId: '1:47594733996:ios:09364dcac91160a274ba09',
    messagingSenderId: '47594733996',
    projectId: 'test-6b603',
    storageBucket: 'test-6b603.firebasestorage.app',
    iosBundleId: 'com.example.loginSignupPages',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-Ce35EtIyql4tgFwTAVVu1XA-mw4JxWU',
    appId: '1:47594733996:web:1fc00c9ced00181b74ba09',
    messagingSenderId: '47594733996',
    projectId: 'test-6b603',
    authDomain: 'test-6b603.firebaseapp.com',
    storageBucket: 'test-6b603.firebasestorage.app',
    measurementId: 'G-LR13RH7LJ5',
  );
}
